/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2023-02-18-bf6bbf1877"
#endif /* AVUTIL_FFVERSION_H */
